export interface LocalEvent {
  id: string;
  title: string;
  date: string;
  time: string;
  location: string;
  category: string;
  emoji: string;
}

export const PLACEHOLDER_EVENTS: LocalEvent[] = [
  {
    id: '1',
    title: 'Heimspiel: 1. FC Heidenheim vs. VfB',
    date: 'Samstag, 16. Mai',
    time: '15:30 Uhr',
    location: 'Voith-Arena, Heidenheim',
    category: 'Sport',
    emoji: '⚽',
  },
  {
    id: '2',
    title: 'VHS Kurs: Italienisch für Anfänger',
    date: 'Montag, 18. Mai',
    time: '18:00 Uhr',
    location: 'Volkshochschule Heidenheim',
    category: 'Bildung',
    emoji: '🎓',
  },
  {
    id: '3',
    title: 'Wochenmarkt Heidenheim',
    date: 'Mittwoch, 21. Mai',
    time: '07:00 Uhr',
    location: 'Marktplatz, Heidenheim',
    category: 'Märkte',
    emoji: '🛒',
  },
  {
    id: '4',
    title: 'Open-Air Konzert: Sommernacht Jazz',
    date: 'Freitag, 23. Mai',
    time: '20:00 Uhr',
    location: 'Schlosspark, Heidenheim',
    category: 'Konzerte',
    emoji: '🎷',
  },
  {
    id: '5',
    title: 'Familientag im Tierpark',
    date: 'Sonntag, 25. Mai',
    time: '10:00 Uhr',
    location: 'Tierpark Heidenheim',
    category: 'Familie',
    emoji: '🦁',
  },
  {
    id: '6',
    title: 'Club Night: Techno & House',
    date: 'Samstag, 24. Mai',
    time: '23:00 Uhr',
    location: 'Club Zentral, Heidenheim',
    category: 'Nightlife',
    emoji: '🎧',
  },
  {
    id: '7',
    title: 'Fotografie-Workshop für Einsteiger',
    date: 'Dienstag, 27. Mai',
    time: '17:00 Uhr',
    location: 'Kunstschule Heidenheim',
    category: 'Workshops',
    emoji: '📷',
  },
  {
    id: '8',
    title: 'Stadtführung: Historisches Heidenheim',
    date: 'Samstag, 31. Mai',
    time: '14:00 Uhr',
    location: 'Treffpunkt Rathaus, Heidenheim',
    category: 'Kultur',
    emoji: '🏛️',
  },
  {
    id: '9',
    title: 'Halbmarathon Brenztal',
    date: 'Sonntag, 1. Juni',
    time: '09:00 Uhr',
    location: 'Startplatz Brenzpark, Heidenheim',
    category: 'Sport',
    emoji: '🏃',
  },
  {
    id: '10',
    title: 'Töpferkurs: Keramik für Erwachsene',
    date: 'Donnerstag, 29. Mai',
    time: '18:30 Uhr',
    location: 'Kreativwerkstatt, Heidenheim',
    category: 'Workshops',
    emoji: '🏺',
  },
  {
    id: '11',
    title: 'Kinderfest am See',
    date: 'Samstag, 7. Juni',
    time: '11:00 Uhr',
    location: 'Riedbad, Heidenheim',
    category: 'Familie',
    emoji: '🎪',
  },
  {
    id: '12',
    title: 'Antikmarkt & Trödelmarkt',
    date: 'Sonntag, 8. Juni',
    time: '08:00 Uhr',
    location: 'Festplatz, Heidenheim',
    category: 'Märkte',
    emoji: '🗿',
  },
  {
    id: '13',
    title: 'Poetry Slam Abend',
    date: 'Mittwoch, 4. Juni',
    time: '20:00 Uhr',
    location: 'Kulturhaus Heidenheim',
    category: 'Kultur',
    emoji: '🎤',
  },
  {
    id: '14',
    title: 'Lateinamerikanischer Tanzabend',
    date: 'Freitag, 6. Juni',
    time: '21:00 Uhr',
    location: 'Tanzstudio Rhythmus, Heidenheim',
    category: 'Nightlife',
    emoji: '💃',
  },
  {
    id: '15',
    title: 'VHS Kurs: Aquarellmalerei',
    date: 'Montag, 2. Juni',
    time: '16:00 Uhr',
    location: 'Volkshochschule Heidenheim',
    category: 'Bildung',
    emoji: '🎨',
  },
  {
    id: '16',
    title: 'Rockband-Konzert: Die Lokalmatadore',
    date: 'Samstag, 14. Juni',
    time: '19:30 Uhr',
    location: 'Stadthalle Heidenheim',
    category: 'Konzerte',
    emoji: '🎸',
  },
  {
    id: '17',
    title: 'Yoga im Park',
    date: 'Sonntag, 15. Juni',
    time: '09:00 Uhr',
    location: 'Brenzpark, Heidenheim',
    category: 'Sport',
    emoji: '🧘',
  },
  {
    id: '18',
    title: 'Vortrag: Nachhaltigkeit im Alltag',
    date: 'Dienstag, 10. Juni',
    time: '19:00 Uhr',
    location: 'Bücherei Heidenheim',
    category: 'Bildung',
    emoji: '🌱',
  },
];
